version: '3'

services:
  client:
    build:
      context: ./path/to/client
    ports:
      - "4200:80"
    depends_on:
      - server-gateway

  microservicio:
    build:
      context: ./path/to/microservicio
    ports:
      - "3000:3000"
    depends_on:
      - server-gateway

  server-gateway:
    build:
      context: ./path/to/server-gateway
    ports:
      - "80:3000"
    depends_on:
      - microservicio
