name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.Docker_User}}
        DOCKER_PASSWORD: ${{secrets.Docker_Password}}

      run: 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build and Push Docker Images
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t jofre159rz/trabajoautonomo:client-$NEW_VERSION /client
        docker build -t jofre159rz/trabajoautonomo:client-latest /client
        docker push jofre159rz/trabajoautonomo:client-$NEW_VERSION
        docker push jofre159rz/trabajoautonomo:client-$latest 
        docker build -t jofre159rz/trabajoautonomo:microservicio-$NEW_VERSION /microservice-solicitud-baja/microservice-solicitud-baja
        docker build -t jofre159rz/trabajoautonomo:microservicio-latest  /microservice-solicitud-baja/microservice-solicitud-baja
        docker push jofre159rz/trabajoautonomo:microservicio-$NEW_VERSION
        docker push jofre159rz/trabajoautonomo:microservicio-latest 
        docker build -t jofre159rz/trabajoautonomo:server-$NEW_VERSION /server
        docker build -t jofre159rz/trabajoautonomo:server-latest  /server
        docker push jofre159rz/trabajoautonomo:server-$NEW_VERSION
        docker push jofre159rz/trabajoautonomo:server-latest 
